version: "3.8"

name: printed
services:
  watch:
    image: dancardin/printed:latest
    build:
      context: .
    restart: always
    command: watch
    volumes:
      - "./:/printed"
      - "./data:/data"

  web:
    image: dancardin/printed:latest
    build:
      context: .
    restart: always
    command: web --host 0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - "./:/printed"
      - "./data:/data"
